0:	learn: 0.9398447	total: 170ms	remaining: 5m 38s
1:	learn: 0.9107559	total: 293ms	remaining: 4m 52s
2:	learn: 0.8837331	total: 406ms	remaining: 4m 30s
3:	learn: 0.8587128	total: 512ms	remaining: 4m 15s
4:	learn: 0.8379013	total: 621ms	remaining: 4m 7s
5:	learn: 0.8163936	total: 737ms	remaining: 4m 4s
6:	learn: 0.7982973	total: 845ms	remaining: 4m
7:	learn: 0.7817987	total: 960ms	remaining: 3m 59s
8:	learn: 0.7662337	total: 1.07s	remaining: 3m 57s
9:	learn: 0.7513519	total: 1.18s	remaining: 3m 54s
10:	learn: 0.7370730	total: 1.3s	remaining: 3m 54s
11:	learn: 0.7259425	total: 1.42s	remaining: 3m 54s
Traceback (most recent call last):
  File "C:\Users\sergi\AppData\Local\Temp\ipykernel_271252\2069214660.py", line 19, in wandb_train
    bst.fit(X_train, y_train)
  File "c:\Users\sergi\anaconda3\envs\olx\Lib\site-packages\catboost\core.py", line 5827, in fit
    return self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sergi\anaconda3\envs\olx\Lib\site-packages\catboost\core.py", line 2400, in _fit
    self._train(
  File "c:\Users\sergi\anaconda3\envs\olx\Lib\site-packages\catboost\core.py", line 1780, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4833, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4882, in _catboost._CatBoost._train
_catboost.CatBoostError: bad allocation